version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres_d
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ${DB_VOLUME}
      - ./db/:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
